name: mp3_player
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^9.0.0
  flutter_downloader: ^1.8.0
  dio: ^5.0.0
  path_provider: ^2.0.0
  sqflite: ^2.0.0
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  just_audio_background: ^0.0.1-beta.17
  provider: ^6.1.5+1
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/musicas.json
